DROP TABLE IF EXISTS STUDENT;
CREATE TABLE STUDENT
(ID INT PRIMARY KEY AUTO_INCREMENT, NAME VARCHAR(255) NOT NULL, SURNAME VARCHAR(255) NOT NULL, AGE INT NOT NULL DEFAULT 0, SEX VARCHAR(255));
INSERT INTO STUDENT ( NAME, SURNAME, SEX) VALUES ('Olek', 'S.', 'MALE');
INSERT INTO STUDENT ( NAME, SURNAME, AGE, SEX) VALUES ('Marek', 'W.', 25, 'MALE');
INSERT INTO STUDENT ( NAME, SURNAME, AGE, SEX) VALUES ('Alina', 'G.', 18, 'FEMALE');
INSERT INTO STUDENT ( NAME, SURNAME, AGE, SEX) VALUES ('Anna', 'F.', 35, 'FEMALE');
INSERT INTO STUDENT ( NAME, SURNAME, AGE, SEX) VALUES ('EWELINA', 'A.', 40, 'FEMALE');
DELETE FROM STUDENT WHERE ID = 10;